name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v5
      with: 
        submodules: 'recursive'

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'graalvm'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build with Gradle Wrapper
      run: chmod +x gradlew && ./gradlew build
    - name: Upload jar without dependencies
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: KoloMITM-1.0-SNAPSHOT.jar
        path: build/libs/KoloMITM-1.0-SNAPSHOT.jar

    - name: Upload Upload jar with dependencies
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: KoloMITM-1.0-SNAPSHOT-all.jar
        path: build/libs/KoloMITM-1.0-SNAPSHOT-all.jar


  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v5
      with: 
        submodules: 'recursive'

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'graalvm'

    - name: Grant executable permission
      run: chmod +x gradlew

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4

